FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN apt-get update && apt-get install -y    \
    gdb                                     \
    cmake                                   \
    libcgns-dev
